//! Deterministic Rust table emission.
//!
//! The baker prints this source on stdout; `cargo xtask generate` places the
//! checked-in copy. Identical ingest and quantize input produces identical
//! bytes: `\n` only, no timestamps, no host paths.

use std::fmt::Write as _;

use crate::quantize::{QuantizedTable, emit_max_err_lsb};
use crate::{Axis, BakeInput};

/// Per-axis lookup named in emitted source. This selects tokens, not a grid.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EmitAxis {
    /// Default BinaryAxis: stored knots, no auxiliary index.
    Binary,
    /// BucketedAxis with `buckets` entries. Generated source calls
    /// `ph_surfaces::bucket_index`; this crate does not depend on `ph-surfaces`.
    Bucketed {
        /// Bucket table length `B`.
        buckets: usize,
    },
}

impl EmitAxis {
    fn is_binary(self) -> bool {
        matches!(self, Self::Binary)
    }

    fn name(self) -> &'static str {
        match self {
            Self::Binary => "BinaryAxis",
            Self::Bucketed { .. } => "BucketedAxis",
        }
    }

    fn index_bytes(self) -> usize {
        match self {
            Self::Binary => 0,
            Self::Bucketed { buckets } => 2 * buckets,
        }
    }
}

/// Samples for the checked-in drift-gate fixture (S4 runtime-rounding 2×2).
const CHECKED_IN_SAMPLES: &str = "0 0 0\n2 0 1\n0 2 1\n2 2 2\n1 1 1\n";

/// Render BinaryAxis × BinaryAxis static tables from a quantized grid.
#[must_use]
pub fn emit_rust(table: &QuantizedTable) -> String {
    emit_rust_with(table, EmitAxis::Binary, EmitAxis::Binary)
}

/// Render static tables for an explicit pairing.
///
/// `PAYLOAD_BYTES` is the referenced element payload using the public
/// runtime formula, not total RAM, flash, binary, or linker cost.
#[must_use]
pub fn emit_rust_with(table: &QuantizedTable, x: EmitAxis, y: EmitAxis) -> String {
    let nx = table.x.len();
    let ny = table.y.len();
    let mut src = String::from("// @generated by `cargo xtask generate`; do not edit by hand.\n\n");
    push_uses(&mut src, x, y);
    src.push('\n');
    let _ = writeln!(src, "static X: [u16; {nx}] = {};", list(&table.x));
    let _ = writeln!(src, "static Y: [u16; {ny}] = {};", list(&table.y));
    src.push_str("#[rustfmt::skip]\n");
    let _ = writeln!(
        src,
        "static VALUES: [[i32; {nx}]; {ny}] = {};",
        grid(&table.values)
    );
    push_indexes(&mut src, x, y);
    let payload = 2 * nx + x.index_bytes() + 2 * ny + y.index_bytes() + 4 * nx * ny;
    let _ = writeln!(src, "\n/// Pairing: {} × {}.", x.name(), y.name());
    src.push_str("/// Referenced element payload, not total RAM, flash, binary, or linker cost.\n");
    let _ = writeln!(src, "pub const PAYLOAD_BYTES: usize = {payload};\n");
    push_surface(&mut src, nx, ny, x, y);
    src.push_str(
        "\n// MAX_ERR_LSB is an i32 value LSB: deviation from supplied samples, not\n\
         // device, accuracy, timing, or flash.\n",
    );
    src.push_str(&emit_max_err_lsb(table.max_err_lsb));
    src
}

/// Source for the checked-in drift-gate fixture.
///
/// S4 rounding example: knots `[0, 2]`, grid `[[0, 1], [1, 2]]`, off-knot
/// sample `(1, 1, 1)`. Host bilinear is 1; runtime X-then-Y is 2;
/// `MAX_ERR_LSB` is 1.
#[must_use]
pub fn checked_in_source() -> String {
    emit_rust(
        &checked_in_input()
            .quantize()
            .expect("checked-in fixture must quantize"),
    )
}

fn checked_in_input() -> BakeInput {
    BakeInput::parse(
        CHECKED_IN_SAMPLES,
        Axis::knots(vec![0, 2]),
        Axis::knots(vec![0, 2]),
        1.0,
    )
    .expect("checked-in fixture must ingest")
}

fn push_uses(src: &mut String, x: EmitAxis, y: EmitAxis) {
    src.push_str("use ph_surfaces::BilinearSurface;\n");
    if x.is_binary() && y.is_binary() {
        return;
    }
    if x.is_binary() || y.is_binary() {
        src.push_str("use ph_surfaces::BinaryAxis;\n");
    }
    src.push_str("use ph_surfaces::BucketedAxis;\n");
    src.push_str("use ph_surfaces::bucket_index;\n");
}

fn push_indexes(src: &mut String, x: EmitAxis, y: EmitAxis) {
    if let EmitAxis::Bucketed { buckets } = x {
        let _ = writeln!(src, "static X_INDEX: [u16; {buckets}] = bucket_index(&X);");
    }
    if let EmitAxis::Bucketed { buckets } = y {
        let _ = writeln!(src, "static Y_INDEX: [u16; {buckets}] = bucket_index(&Y);");
    }
}

fn push_surface(src: &mut String, nx: usize, ny: usize, x: EmitAxis, y: EmitAxis) {
    if x.is_binary() && y.is_binary() {
        let _ = writeln!(
            src,
            "pub static SURFACE: BilinearSurface<{nx}, {ny}> =\n    BilinearSurface::new(&X, &Y, &VALUES);"
        );
        return;
    }
    let _ = writeln!(
        src,
        "pub static SURFACE: BilinearSurface<{nx}, {ny}, {}, {}> =\n    BilinearSurface::from_axes(\n        {},\n        {},\n        &VALUES,\n    );",
        axis_ty(x, nx),
        axis_ty(y, ny),
        axis_ctor(x, "X"),
        axis_ctor(y, "Y"),
    );
}

fn axis_ty(axis: EmitAxis, n: usize) -> String {
    match axis {
        EmitAxis::Binary => format!("BinaryAxis<{n}>"),
        EmitAxis::Bucketed { buckets } => format!("BucketedAxis<{n}, {buckets}>"),
    }
}

fn axis_ctor(axis: EmitAxis, name: &str) -> String {
    match axis {
        EmitAxis::Binary => format!("BinaryAxis::new(&{name})"),
        EmitAxis::Bucketed { .. } => format!("BucketedAxis::new(&{name}, &{name}_INDEX)"),
    }
}

fn list<T: core::fmt::Display>(values: &[T]) -> String {
    let mut out = String::from("[");
    for (i, v) in values.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        let _ = write!(out, "{v}");
    }
    out.push(']');
    out
}

fn grid(values: &[Vec<i32>]) -> String {
    let mut out = String::from("[\n");
    for row in values {
        out.push_str("    ");
        out.push_str(&list(row));
        out.push_str(",\n");
    }
    out.push(']');
    out
}

#[cfg(test)]
mod tests {
    use super::{EmitAxis, checked_in_source, emit_rust, emit_rust_with};
    use crate::{Axis, BakeInput};
    use ph_surfaces::BilinearSurface;

    mod fixture {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/generated/rounding.rs"
        ));
    }

    fn corners() -> crate::quantize::QuantizedTable {
        BakeInput::parse(
            "0 0 1.5\n10 0 2.5\n0 5 3.5\n10 5 4.5\n",
            Axis::knots(vec![0, 10]),
            Axis::knots(vec![0, 5]),
            1000.0,
        )
        .unwrap()
        .quantize()
        .unwrap()
    }

    #[test]
    fn binary_emission_is_byte_stable_and_names_the_bound_unit() {
        let table = corners();
        let a = emit_rust(&table);
        let b = emit_rust(&table);
        assert_eq!(a, b);
        assert!(!a.contains('\r'));
        assert!(!a.contains('\\'));
        assert!(a.contains("static X: [u16; 2] = [0, 10];"));
        assert!(a.contains("static Y: [u16; 2] = [0, 5];"));
        assert!(a.contains("static VALUES: [[i32; 2]; 2] = ["));
        assert!(a.contains("[1500, 2500],"));
        assert!(a.contains("[3500, 4500],"));
        assert!(a.contains("Pairing: BinaryAxis × BinaryAxis."));
        assert!(a.contains("pub const PAYLOAD_BYTES: usize = 24;"));
        assert!(a.contains("BilinearSurface::new(&X, &Y, &VALUES)"));
        assert!(a.contains(&crate::emit_max_err_lsb(table.max_err_lsb)));
        assert!(a.contains("i32 value LSB"));
        assert_eq!(
            24,
            BilinearSurface::<2, 2>::PAYLOAD_BYTES,
            "emitted PAYLOAD_BYTES must match the public runtime constant"
        );
    }

    #[test]
    fn checked_in_fixture_compiles_against_the_runtime() {
        assert_eq!(
            fixture::PAYLOAD_BYTES,
            BilinearSurface::<2, 2>::PAYLOAD_BYTES
        );
        assert_eq!(fixture::SURFACE.evaluate(1, 1), Ok(2));
        assert_eq!(fixture::MAX_ERR_LSB, 1);
    }

    #[test]
    fn checked_in_fixture_is_the_s4_rounding_example() {
        let src = checked_in_source();
        assert_eq!(src, checked_in_source());
        assert!(src.contains("pub const MAX_ERR_LSB: i32 = 1;"));
        assert!(src.contains("pub const PAYLOAD_BYTES: usize = 24;"));
        assert!(src.contains("[0, 1],"));
        assert!(src.contains("[1, 2],"));
        assert!(!src.contains('\r'));
    }

    #[test]
    fn bucketed_emission_calls_the_public_bucket_index() {
        let table = corners();
        let src = emit_rust_with(&table, EmitAxis::Bucketed { buckets: 2 }, EmitAxis::Binary);
        assert!(src.contains("use ph_surfaces::bucket_index;"));
        assert!(src.contains("static X_INDEX: [u16; 2] = bucket_index(&X);"));
        assert!(!src.contains("Y_INDEX"));
        assert!(src.contains("Pairing: BucketedAxis × BinaryAxis."));
        assert!(src.contains("pub const PAYLOAD_BYTES: usize = 28;"));
        assert!(src.contains("BucketedAxis<2, 2>"));
        assert!(src.contains("BinaryAxis<2>"));
        assert!(src.contains("BucketedAxis::new(&X, &X_INDEX)"));
        assert!(src.contains("BinaryAxis::new(&Y)"));
        assert_eq!(
            src,
            emit_rust_with(&table, EmitAxis::Bucketed { buckets: 2 }, EmitAxis::Binary)
        );
    }

    #[test]
    fn both_axes_bucketed_names_both_indexes() {
        let table = corners();
        let src = emit_rust_with(
            &table,
            EmitAxis::Bucketed { buckets: 2 },
            EmitAxis::Bucketed { buckets: 2 },
        );
        assert!(src.contains("static X_INDEX: [u16; 2] = bucket_index(&X);"));
        assert!(src.contains("static Y_INDEX: [u16; 2] = bucket_index(&Y);"));
        assert!(!src.contains("BinaryAxis"));
        assert!(src.contains("pub const PAYLOAD_BYTES: usize = 32;"));
    }
}
